[build]
  command = "yarn prisma:generate && yarn build"
  publish = "dist"  

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200