[build]
  command = "yarn build"  # if you have a build step
  publish = "dist"        # or wherever your static assets are, if any

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200